[Session] 세션 상세 - 발표 개요
droidknights/DroidKnights2023_App pull request #217
Opened 2023-08-17 12:26 UTC by JeonK1

## Issue
- close #139

## Overview (Required)
- 발표 개요 내용이 존재하면 해당 텍스트를 보여준다.

## Screenshot
Before | After
![overview2](https://github.com/droidknights/DroidKnights2023_App/assets/18674395/a2537205-43a3-487e-82f8-0f957367177e) | ![Overview](https://github.com/droidknights/DroidKnights2023_App/assets/18674395/2f345323-9760-4b41-9312-8d844b6cc544)

<img src="" width="300" /> | <img src="" width="300" />

2023-08-17 13:10 UTC, wisemuji requested changes
발표 개요 내용이 존재하는지 분기 처리까지 해주셨군요 👍 
몇 가지 코멘트 확인 부탁드립니다.

2023-08-17 14:50 UTC, taehwandev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
> +}
개인적으로 함수의 순서는
ViewModel을 전달 받는 함수 하나(State를 전달 받을 수도 있을거구요.
```
@Composable
fun 외부에서 보여지는 함수() {}

@Composable
private/internal fun 프리뷰를 위한 함수() {}

@Preview
@Composable
internal fun Preview에 함수이름() {}
```

요런식으로 구반하고 사용하고 있습니다.

위치는 프리뷰가 가장 아래이고요. 아무래도 프리뷰를 통해 이것저것 UI 확인이 가능하기도하니 테스트 코드도 포함될수도 있고요.

2023-08-18 11:28 UTC, JeonK1 commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
> +}
확실히 테스트코드 영역을 별도로 분리하니 코드리뷰시에 불필요한 테스트코드를 확인하는 일을 줄일 수 있어서 더욱 좋아보입니다.
코멘트 감사합니다. 반영하였습니다. https://github.com/droidknights/DroidKnights2023_App/pull/217/commits/4f8325da587a1f39ab540e83bb9aa08766e5fff9

2023-08-18 11:31 UTC, JeonK1 commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
> +        }
Preview 코드 작성하면서 개요 데이터가 존재할 때와 존재하지 않을때의 Preview를 각각 작성해야할지 하나하나 작성하면 코드가 길어질 것 같으니 안해야할지 고민하다 대표 값 하나만 작성했었는데요..!
덕분에 PreviewParameter 를 적용하여 이러한 걱정들을 해소할 수 있었습니다.
감사합니다. 반영하였습니다! https://github.com/droidknights/DroidKnights2023_App/pull/217/commits/a16a7534e0285ae53d9b8452265c6b6a01e70a38

2023-08-18 13:13 UTC, wisemuji commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionDetailScreen.kt
> +    title = "세션 제목은 세션 제목 - 개요 있음",
```suggestion
    title = "세션 제목은 세션 제목 - 개요 없음",
```

2023-08-19 02:26 UTC, merged