[Session] 키노트 세션을 클릭하면 앱이 죽는 현상
droidknights/DroidKnights2023_App pull request #218
Opened 2023-08-17 16:11 UTC by koreatlwls

## Issue
- close #210 

## Overview (Required)
- 세션 목록의 키노트 아이템을 클릭하면 앱이 종료됨

## Screenshot
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/61337202/09f7d227-2f15-46de-8a4d-6411c33f0ee0" width="300" />

2023-08-17 23:26 UTC, laco-dev requested changes

2023-08-17 23:26 UTC, laco-dev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +private fun KnightsCardContent(
SessionCard에 대한 내용이기 때문에 `SessionCardContent` 라는 이름이 적절해 보입니다

2023-08-17 23:26 UTC, laco-dev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
예외가 발생하는 원인이 무엇이었을까요?

`세션 아이디 == "1"` 이라는 방법이 예외가 발생하지 않도록 하는 근본적인 원인을 해결하고있을까요?

2023-08-18 01:50 UTC, taehwandev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +                )
Spacer대신
text에 Modifier padding 사용하셔도 됩니다

2023-08-18 01:52 UTC, taehwandev commented
@laco-dev 기본 띄어쓰기 조건이 달라보이네요. 불필요한 정렬이 많은데 요거 기본 설정 안내도 함께 부탁드려요

2023-08-18 03:34 UTC, koreatlwls commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
키노트에 해당하는 카드도 onClick을 줘서 SessionDetail 화면으로 이동하는 경우 SessionDetail에서
speakers.first().imageUrl 이부분 때문에 collection 예외가 발생하는 것으로 확인하였습니다.

2023-08-18 12:36 UTC, laco-dev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
네, 그러면 어떻게 해결하는게 또다른 문제가 생기는 것을 막을 수 있을지 답을 찾아보세요

2023-08-18 13:08 UTC, koreatlwls commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +private fun KnightsCardContent(
2d81410b053a52d99c876677e4541db3de5346f0

2023-08-18 13:08 UTC, koreatlwls commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +private fun KnightsCardContent(
2d81410b053a52d99c876677e4541db3de5346f0

2023-08-18 13:13 UTC, koreatlwls commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
1e17d4b0849a6eb44afa7a11d2c3abcadae6cc15
![12z](https://github.com/droidknights/DroidKnights2023_App/assets/61337202/a241d56c-14c7-4856-abbf-b043e93d95f4)

2023-08-18 15:20 UTC, laco-dev commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
@koreatlwls 
실제로 문제가 발생하는 지점을 수정하는 방법도 좋습니다. 👍🏻 
한 가지 고민 해 볼 수 있는 점은 만약 키노트의 아이디가 "1"이 아닌 "2"로 내려올 수 있답니다.

클릭이 가능하다라는 조건을 아래와 같이 접근 해 보면 어떨까요?
"상세화면에 실제로 보여줄 데이터가 없다면 -> 상세 화면을 실행시키지 않는다"

2023-08-20 05:26 UTC, koreatlwls commented on feature/session/src/main/java/com/droidknights/app2023/feature/session/SessionCard.kt
> +    if (session.id == "1") {
e5264f9761db4b3d6256b4baa970a8a8a5c0e6cd

넵 content가 빈값일 경우 실행시키지 않는다로 수정해보았습니다.

2023-08-20 08:57 UTC, laco-dev approved these changes
네, 확인했습니다

감사합니다

2023-08-20 08:57 UTC, merged