[Home] 후원사 카드 내부 로고 배치 수정
droidknights/DroidKnights2023_App pull request #219
Opened 2023-08-17 17:26 UTC by koreatlwls

## Issue
- close #161 

## Overview (Required)
- 기존 후원사 카드 내부 로고 배치 수정
- 자동/무한 스크롤 기능 제거
    - 이 기능은 더 이상 유효하지 않으므로 제거합니다.

## Screenshot
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/61337202/ed792b4e-9a3d-432b-8078-2253a02c3589" width="300" />

2023-08-17 23:29 UTC, laco-dev commented
충돌 발생 원인
: 이미지가 Clickable 하도록 변경되었습니다.
- https://github.com/droidknights/DroidKnights2023_App/pull/215#pullrequestreview-1583632800

2023-08-17 23:54 UTC, laco-dev requested changes

2023-08-17 23:54 UTC, laco-dev commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +    Box(modifier = Modifier.padding(start = 3.dp)) {
`padding(start = 3.dp)`는 어떤 목적으로 추가되었을까요?

2023-08-17 23:54 UTC, laco-dev commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +        )
![image](https://github.com/droidknights/DroidKnights2023_App/assets/28249981/9025c3da-c282-4fb5-b367-581334a665e3)

로고들이 가운데를 기준으로 배치되면 좋을 것 같습니다.
*지금은 왼쪽에 쏠려있음

2023-08-17 23:54 UTC, laco-dev commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +                ),
만약 데이터가 스크롤이 가능한 정도로 충분히 많다면 오른쪽으로 스크롤을 하게 되면 어떻게 될까요?

2023-08-18 01:53 UTC, taehwandev commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +    val goldSponsors = sponsors.filter { it.grade == Sponsor.Grade.GOLD }
Recomposition 이 발생하면 이 코드는 어떻게 동작할까요?
적절한 방법을 활용해주세요.
remember 처리

2023-08-18 03:30 UTC, koreatlwls commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +    Box(modifier = Modifier.padding(start = 3.dp)) {
NetworkImage 의 Shadow 짤림 방지를 위해 3.dp를 넣고 그만큰 다른부분에서의 간격도 조정하였습니다.

2023-08-18 03:31 UTC, koreatlwls commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +                ),
아마 하단의 LazyRow만 scroll한 영역이 왼쪽부분이 줄어든체로 스크롤이 될껍니다.

2023-08-18 13:01 UTC, wisemuji commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +        )
후원사가 4개 고정 배치 기준으로 만들어진 시안이라 SponsorLogo의 size를 fix하지 않고, 부모 영역에 맞춰 늘리는 것이 적절해보입니다.  SponsorLogo 컴포저블의 `.size(84.dp)`를 제거해주세요!

2023-08-18 13:30 UTC, koreatlwls commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +        )
> 후원사가 4개 고정 배치 기준으로 만들어진 시안이라 SponsorLogo의 size를 fix하지 않고, 부모 영역에 맞춰 늘리는 것이 적절해보입니다. SponsorLogo 컴포저블의 `.size(84.dp)`를 제거해주세요!

단순히 .size(84.dp) 만 지우게 된다면 화면에서 당근마켓 후원사만 보이게됩니다

2023-08-20 05:17 UTC, koreatlwls commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +    val goldSponsors = sponsors.filter { it.grade == Sponsor.Grade.GOLD }
9e5bbcb74f80ec684a5958baaa3b36bf7bb13af6
rememberUpdateState 처리하였습니다.

2023-08-20 05:19 UTC, koreatlwls commented on feature/home/src/main/java/com/droidknights/app2023/feature/home/SponsorCard.kt
> +        )
170f913eee3c8e90fd6c5ce5ff044dc78df82468
<img width="224" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/61337202/ab307af5-5820-49df-a64a-fbea0a8122f0">

2023-08-21 10:17 UTC, laco-dev approved these changes
고생하셨습니다.

다음 작업에 앞서 현재PR은 우선 병합하도록 하겠습니다

2023-08-21 10:17 UTC, merged