[북마크] 북마크한 세션 목록 화면 구현
droidknights/DroidKnights2023_App pull request #220
Opened 2023-08-17 18:49 UTC by toastmeister1

## Issue
- close #198

## Overview (Required)
북마크한 세션 목록들을 화면에 표시하는 기능을 구현합니다
- 북마크한 목록이 비었을 경우의 화면을 구현합니다 (디자인에는 없지만 임의적으로 구현했습니다.
- 북마크한 아이템들을 화면에 표시하도록 구현합니다.
- 편집 관련 기능구현을 하지 않았으나 (Ui 포함) 편집 기능을 고려하여 코드를 작성했습니다.

## Links

## Screenshot
<table style="width:100%">
   <tr>
      <th>빈 화면 / Empty</th>
      <th>북마크 아이템 표현(필터기능 해제한화면 입니다)</th>
   </tr>
   <tr>
      <td>
         <video src="https://github.com/droidknights/DroidKnights2023_App/assets/53253298/ae2e5f57-a04d-41fe-9c09-3f06cf96c8b3"></video>
      </td>
      <td>
         <video src="https://github.com/droidknights/DroidKnights2023_App/assets/53253298/b01bd900-32b2-4706-bac0-ecfcba221412"></video>
      </td>
   </tr>
</table>

2023-08-18 14:02 UTC, wisemuji requested changes
편집 기능도 고려하여 완성도 높은 기능을 구현해주셨네요 👏 
몇 가지 코멘트 확인을 부탁드립니다.

2023-08-18 14:02 UTC, wisemuji commented on feature/bookmark/src/main/res/values/string.xml
> +</resources>
다음 설정 옵션을 활성화하여 EOF 경고를 없애주세요 :slightly_smiling_face:
- File > Preferences > Editor > General > Ensure every saved file ends with a line break

2023-08-18 14:07 UTC, laco-dev requested changes
북마크 화면을 한번에 구현을 해주셨네요. 고생 많으셨습니다

여러 로직을 한번에 수정 요청드리기 보다는 부분적으로 나눠서 드리면 좋을 것 같네요.
또한 UI 구현의 관점보다는 기능 관점에서의 피드백을 중점적으로 드렸습니다.

2023-08-18 14:07 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +            _bookmarkUiState.value = BookmarkUiState.Success()
지금 구조에서는 Success가 불필요하게 두번 데이터가 전달됩니다.
- Success(비어있는 아이템)
- Success(필터링 된 아이템)

또한 UI 상태를 만들기 위한 로직이 다소 높은 복잡도를 띄고 있습니다.
아래 내용을 참고해서 개선 해 보면 좋겠습니다

```kotlin
val bookmarkedSessions = ???
...
combine(
   bookmarkedSessions,
   bookmarkUiState
) { 
   Loading -> Success(...)
   Success -> map
}
```

2023-08-18 14:07 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/listitem/BookmarkCard.kt
> +        headerSection = @Composable {
결국 BookmarkCard가 그려야 하는 데이터는 이곳에 정의되어있는 header, body, footer를 사용합니다.

그렇다면 BookmarkCard가 이러한 슬롯을 제공할 정도의 추상화가 필요한 상황일까요?

2023-08-18 14:07 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkScreen.kt
> +        }
컴포저블 함수는 컴포즈 컴파일러에 의해 실행 코드의 블록이 계속해서 변경됩니다.
그렇기 때문에 return문을 사용하는 것은 지양해야 합니다.

2023-08-18 14:07 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +        bookmarkUiState.value.ifStateIsSuccess { state ->
`ifStateIsSuccess` 는 if 조건문으로 사용했을때와 달리 좋은 이점을 제공하고 있을까요?

아래 코드와 비교하면 어떤 부분이 가독성이 좋을까요?
*물론 개발자 취향의 영역일 수는 있습니다

```kotlin
fun clickEditButton() {
    val uiState = bookmarkUiState.value
    if (uiState !is BookmarkUiState.Success) {
        return
    }
    _bookmarkUiState.value = uiState.copy(
        isEditMode = uiState.isEditMode.not(),
        bookmarks = uiState.bookmarks.map { it.copy(isEditMode = it.isEditMode.not()) }
    )
}
...
```

2023-08-20 04:17 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/listitem/BookmarkCard.kt
> +}
f4df5dac36e70e0a6da126111992ce6f5a9d4dec 에서 수정 완료했습니다!

2023-08-20 04:17 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkUiState.kt
> +data class BookmarkItemState(
83634a27a590f0da93c336f14e85c8bf282abbb9 에서 수정 완료했습니다

2023-08-20 04:31 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkUiState.kt
> +    val time: LocalTime,
평소 UiState는 무조건 어느 모델에 연관되지 않는것이 좋다는 생각으로 개발했었는데
돌이켜보니 로직 작성의 불편함, Session이 가지고 있는 값들 대부분을 사용하고 있어 
8738f1ceb8f716e9adf50f51dc27afae1e2ea84c 에서 해당 클래스가 Session을 그대로 소유하고, Ui에 필요한 값을 필드로 노출하는 방향으로 수정했습니다!

2023-08-20 04:37 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkUiState.kt
> +    val isEditMode: Boolean
Success는 TopAppBar에서 편집모드 인지를 판별하는 값이고
Item은 북마크 아이템들이 편집모드 인지를 판별하는 값입니다

TopAppBar관점에서 봤을때 어색한것 같아 8738f1ceb8f716e9adf50f51dc27afae1e2ea84c 에서 `isEditButtonSelected`로 수정했습니다!

2023-08-20 04:39 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +            _bookmarkUiState.value = BookmarkUiState.Success()
Flow 사용이 익숙치가 않아 작성하면서 어려움이 있었는데 힌트 주셔서 감사합니다!
a6e0f37d4db26b6d845cab29601f5dd7c13dd47d 에서 개선했습니다! (+ 테스트코드도 작성 해봤습니다)

2023-08-20 04:44 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/listitem/BookmarkCard.kt
> +        headerSection = @Composable {
음.. 재사용에만 너무 초점을 맞추고 구현했었네요
생각해보니 추상화를 통해 레이어가 추가 되는것은 사용하는 사람이 혼란에 빠질 수 있을것 같네요

f0d595f73c748f9d933457af806bc11095469cab 에서 수정했습니다

2023-08-20 04:52 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/listitem/BookmarkCard.kt
> +package com.droidknights.app2023.feature.bookmark.listitem
평소 패키지 분리에 있어서 생각이 부족했네요!
fb0985bc6cdacc17f84d0ab6d601a49db76f7de3 에서 수정했습니다

2023-08-20 04:56 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/text/RoomText.kt
> +internal fun RoomText(
음.. RoomText를 designSystem에 넣기에는 파라미터에 Room이라는 모델이 있어 
**모듈 의존성을 추가**해야 해서 좋은 방향이 아닌것 같다는 생각이 들어 어디에 공통 컴포넌트를 두어야 할지 고민이 됩니다

혹시 이 부분에 있어 힌트 주시면 감사하겠습니다 🙇‍♂️

2023-08-20 05:01 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +                bookmarks = state.bookmarks.map { it.copy(isEditMode = state.isEditMode.not()) }
TopAppBar / 북마크리스트 각각 두 곳에서 사용하는것이였는데

TopAppBar에서 편집 버튼이 눌렸을경우 / 아닌경우 를 나타내고
Item에서 편집상태일경우 / 아닌경우 를 나타내기 위함 이었습니다

이 부분이 어색하다고 느껴서
8738f1ceb8f716e9adf50f51dc27afae1e2ea84c 에서 `isEditButtonSelected` 로 변경하여 TopAppBar에서의 상태를 나타내도록 수정했습니다!

2023-08-20 05:05 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +}
이 부분은 하단에 리뷰 https://github.com/droidknights/DroidKnights2023_App/pull/220#discussion_r1298446561 와 연관 지어서 
8738f1ceb8f716e9adf50f51dc27afae1e2ea84c 에서
BookmarkItemState가 index를 값을 가지도록 하고 sequence를 필드로 노출하도록 수정해봤습니다!

2023-08-20 05:13 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +            sessions.value = getSessionsUseCase()
실행 순서에 관한 수정은 아니지만 GetBookmarkedSessionIdsUseCase와 GetSessionsUseCase를 통해 북마크된 세션들을 가져오는 
`GetBookmarkedSessionsUseCase`를 만들어서 해당 로직을 개선해봤습니다!

a6e0f37d4db26b6d845cab29601f5dd7c13dd47d

2023-08-20 05:18 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkViewModel.kt
> +        bookmarkUiState.value.ifStateIsSuccess { state ->
음.. 코드의 양이 준다는 이점이 있지만
코드를 보는 사람에게는 `ifStateIsSuccess`를 알아야 한다는 단점이 있겠네요!
8738f1ceb8f716e9adf50f51dc27afae1e2ea84c에서 수정했습니다!

2023-08-20 09:05 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/text/RoomText.kt
> +internal fun RoomText(
core-ui 모듈과 core-desgisystem의 모듈 두개가 있습니다.

디자인 시스템은 디자이너와 약속한 규칙을 테마, 속성, 컴포넌트화 하여 만들고
core-ui의 경우 각 ui 모듈에서 사용하기 위한 공통 컴포넌트를 지원합니다.

2023-08-20 09:12 UTC, laco-dev commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/BookmarkUiState.kt
> +    val time: LocalTime,
네 UI 상태가 어떠한 모델과의 의존성을 분리한다는 점은 좋은 관점입니다.

그런데 이 말은 반대로 말하면 UI 상태를 뷰모델이 아닌 UI 그 자체에 커플링을 만든다는 것을 의미합니다.
즉 비즈니스 로직과 관련한 UI 상태를 구현하는 것이 아닌 UI 로직 자체를 구현하게 됩니다.

가령 유저 화면에 대한 UI 상태를 작성한다면 앞서 두가지는 다음과 같이 표현할 수 있습니다.

```kotlin
// UI 그 자체를 그리기 위한 UI 상태
data class UserUiState(
   val isLoading: Boolean,
   val isBottomSheetExpanded: Boolean,
   val firstTitle: String,
   val secondTitle: String,
   val isUserIconVisible: Boolean
   val ...
)


// 비즈니스 UI 상태와 순수 UI를 분리
data class UserUiState(
   val user: User?,
)

data class UserState(user: User) {
   val isExpanded: Boolean
   ...
}
```

이 내용은 팀마다 다르기 때문에 무엇이 정답이라고 할 수는 없습니다.
아래 문서를 참고 해 주세요
https://developer.android.com/topic/architecture/ui-layer/stateholders?hl=ko

2023-08-20 11:52 UTC, toastmeister1 commented on feature/bookmark/src/main/java/com/droidknights/app2023/feature/bookmark/text/RoomText.kt
> +internal fun RoomText(
평소 구현할때 어느기준까지 디자인 시스템모듈에 들어가야 하는지 고민했었는데
core-ui와 같은 모듈로 이런 부분을 해소할 수 있겠네요

125a74bf3a54c790e86b6902a18a4adcf00e16b9 에서 수정 완료했습니다!

2023-08-21 13:16 UTC, wisemuji approved these changes
많은 코멘트 반영하시느라 고생 많으셨습니다 🙇 👏

2023-08-21 13:16 UTC, wisemuji commented on core/domain/src/test/java/com/droidknights/app2023/core/domain/usecase/GetBookmarkedSessionsUseCaseTest.kt
> +                    bookmarkedSessions.map { it.id } shouldContainAll expected
정렬 로직도 테스트하면 어떨까요?

2023-08-21 13:57 UTC, toastmeister1 commented on core/domain/src/test/java/com/droidknights/app2023/core/domain/usecase/GetBookmarkedSessionsUseCaseTest.kt
> +                    bookmarkedSessions.map { it.id } shouldContainAll expected
넵 정렬로직도 중요한 부분이니 테스트 하는게 맞네요
dd18b7692b03b88cc10edac1aa9c1f4856ce0d39 에서 추가했습니다!

그런데 한가지 질문이 있습니다!
위 커밋에서는 테스트를 Then을 하나 더 추가하도록 구현을 했는데

**만약 리스트의 순서가 섞인것을 가정**한 경우를 추가적으로 테스트하고 싶다면 아래의 방법이 맞는지 궁금합니다!
1. 순서가 섞인 suffledList(mock 데이터)를 하나 더 만든다
2. FakeRepo, UseCase를 하나 더 생성한다
3. GWT 테스트 케이스를 하나 더 만든다

2023-08-21 14:14 UTC, laco-dev approved these changes
고생 많으셨습니다.

@wisemuji 
아래 커멘트 확인되셨으면 병합 부탁드립니다.
https://github.com/droidknights/DroidKnights2023_App/pull/220#discussion_r1300093304

2023-08-21 14:19 UTC, toastmeister1 commented
도와드린것보다 두분께 많은 도움을 받았네요 😅
짧지만 많이 배웠습니다 감사합니다!

컨퍼런스 성공적으로 마치시길 바랄게요 :)

2023-08-21 14:20 UTC, merged

2023-08-21 14:21 UTC, toastmeister1 commented on core/domain/src/test/java/com/droidknights/app2023/core/domain/usecase/GetBookmarkedSessionsUseCaseTest.kt
> +                    bookmarkedSessions.map { it.id } shouldContainAll expected
어떤 맥락인지 이해가 가네요!
답변 감사합니다!