[feature/oss_license]: Add OssLicense Feature
droidknights/DroidKnights2023_App pull request #230
Opened 2023-08-20 14:25 UTC by KwakEuiJin

## Issue
- close #155

## Overview (Required)
- Implements an open source library card button
    - 기존에 존재하던 KnightsCard의 활용하였으며, Dark Mode시에도 색상 변경이 없도록 강제하였습니다.
    - oss-license library의 경우 app module에서 사용해야하는 것으로 알고있습니다. 그렇기에 app module에서 구현 로직을 생성 후 navigation module을 통해 feature:setting에서 접근 가능하도록 구현하였습니다.

- oss-license MenuActivity ScreenShot
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/93872496/69591a5a-9fc1-4ad4-9311-b6a10b68e30c" width="300" />

## Screenshot
Before | After
:--: | :--:
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/93872496/bba7c698-bfef-4428-ac92-4c69dd4e5e03" width="300" /> | <img src="https://github.com/droidknights/DroidKnights2023_App/assets/93872496/1e8ed066-346f-4e38-aa9b-7b5eea084c17" width="300" />

2023-08-21 14:41 UTC, wisemuji requested changes
고생 많으셨습니다 🙇 
몇 가지 코멘트 확인 부탁드립니다.

2023-08-21 14:41 UTC, wisemuji commented on app/src/main/java/com/droidknights/app2023/navigation/NavigatorModule.kt
> +}
NavigationProvider를 활용하는 아이디어도 좋지만 혹시 NowInAndroid에서 OssLicensesMenuActivity를 어떻게 띄우고 있는지 참고해보시면 어떨까요? 

- https://github.com/android/nowinandroid/blob/12642c9110a65cba919849a99ad0d21e861f646b/feature/settings/src/main/java/com/google/samples/apps/nowinandroid/feature/settings/SettingsDialog.kt#L267
- https://github.com/android/nowinandroid/blob/12642c9110a65cba919849a99ad0d21e861f646b/feature/settings/build.gradle.kts#L29

2023-08-21 14:41 UTC, wisemuji commented on feature/setting/src/main/java/com/droidknights/app2023/feature/setting/opensource/OpenSourceCard.kt
> +            .padding(horizontal = 8.dp)
부모에서 Padding을 주고 있기 때문에 제거해도 됩니다.

2023-08-21 14:41 UTC, wisemuji commented on feature/setting/src/main/java/com/droidknights/app2023/feature/setting/opensource/OpenSourceCard.kt
> +            )
Description은 Figma 상에서 샘플 텍스트로 선언되어있는 뷰라 현재는 활용되고 있지 않아서 제거해주셔야 할 것 같아요.
미리 안내드리지 못해서 죄송합니다 😅
뷰 배치는 따로 변경하지 않으셔도 되고, 자연스럽게 조절해주셔도 됩니다.

2023-08-22 01:19 UTC, KwakEuiJin commented on app/src/main/java/com/droidknights/app2023/navigation/NavigatorModule.kt
> +}
아하 이 부분 제가 잘못알고있었네요, plugin id만 app/build.gradle.kts 에 추가하고 navigation 활용한 부분은 지웠습니다.

2023-08-22 01:19 UTC, KwakEuiJin commented on feature/setting/src/main/java/com/droidknights/app2023/feature/setting/opensource/OpenSourceCard.kt
> +            )
넵넵 description만 지웠습니다~!!

2023-08-22 08:22 UTC, KwakEuiJin commented
코드 리뷰 달아주셔서 감사합니다 🙇‍♂️
코멘트 달아주신 부분 수정 완료하여 푸시하였습니다. 
시간되실 때 확인해주시면 감사하겠습니다 🌟

2023-08-22 13:53 UTC, wisemuji approved these changes
고생 많으셨습니다 🙇 
@laco-dev 확인해주시면 감사하겠습니다.

2023-08-23 02:34 UTC, KwakEuiJin commented
@laco-dev 
확인해주시면 감사하겠습니다!!

2023-08-23 02:45 UTC, merged