placeholder 이미지 사진 core-ui 모듈 이동
droidknights/DroidKnights2023_App pull request #237
Opened 2023-08-23 23:36 UTC by Cjsghkd

## Issue
- close #140 

## Overview (Required)
- designsystem -> core-ui 모듈로 placholder 이미지 사진 이동

2023-08-24 00:26 UTC, Cjsghkd commented
@wisemuji 
오류를 해결하면서 지금은 사용을 안해서 designsystem <- core-ui 로 참조되던 것을 반대로 바꿨는데, 
혹시 designsystem이 core-ui에 사용될 예정인가요?

2023-08-24 08:36 UTC, wisemuji requested changes
고생 많으셨습니다 🙇 
몇 가지 코멘트 확인 부탁드립니다.

2023-08-24 08:36 UTC, wisemuji commented on core/designsystem/build.gradle.kts
> +
> 오류를 해결하면서 지금은 사용을 안해서 designsystem <- core-ui 로 참조되던 것을 반대로 바꿨는데,
혹시 designsystem이 core-ui에 사용될 예정인가요?

의존성 방향을 바꾸신 이유가 잘 이해되지 않습니다...! 더 자세히 설명해주실 수 있을까요?
designsystem과 core-ui의 역할에 대해서는 다음 코멘트를 참고해보시겠어요?
- https://github.com/droidknights/DroidKnights2023_App/pull/220#discussion_r1299340723

2023-08-24 08:36 UTC, wisemuji commented on core/ui/src/main/res/drawable-xxxhdpi/placeholder_speaker.png
`drawable-hdpi`, `drawable-xhdpi` 등 다양한 해상도별 이미지가 `drawable-xxxhdpi` 하나에만 옮겨졌습니다. 또 이 이미지는 `xxxhdpi`가 아니라 `hdpi` 이미지인 것으로 보이네요.

2023-08-24 08:44 UTC, wisemuji commented on core/designsystem/build.gradle.kts
> +
혹시 NetworkImage에서 `R.drawable.placeholder_speaker`를 참조하고 있는 것을 해결하기 위한 목적이시라면, 해당 이미지는 단순 Preview 노출 시 활용될 목적이였으므로 참조를 제거하셔도 됩니다. `R.drawable.placeholder_speaker` 대신 `ColorPainter`를 활용해보는 것도 방법이 될 수 있겠네요.

2023-08-24 10:49 UTC, Cjsghkd commented
@wisemuji 넵! 수정했습니다!

2023-08-24 12:13 UTC, wisemuji requested changes

2023-08-24 12:13 UTC, wisemuji commented on core/ui/src/main/res/drawable-xxhdpi/placeholder_speaker.png
<img width="194" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/dca3c39c-9662-4da2-9f6e-ecd17189172e">

새로 추가된 이미지들 중 일부에 9-패치 파일처럼 가장자리 그래픽이 생겼습니다...! 
기존의 이미지들을 단순 옮겨만 주시면 됩니다.

`drawable-xxxhdpi/placeholder_speaker.png`는 잘 옮겨졌습니다.
<img width="1146" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/efc3e56f-a3ae-451a-9b8e-cac05210813d">

2023-08-24 12:50 UTC, Cjsghkd commented on core/ui/src/main/res/drawable-xxhdpi/placeholder_speaker.png
@wisemuji 죄송합니다ㅏ 수정했습니다!

2023-08-25 14:12 UTC, wisemuji approved these changes
좋습니다! 고생 많으셨습니다 👏

2023-08-25 14:13 UTC, merged