Fix/prevent multiple click
droidknights/DroidKnights2023_App pull request #243
Opened 2023-08-30 17:00 UTC by kisa002

## Overview (Required)

컴포넌트를 연타할 때 발생하는 중복 호출 이슈를 수정하였습니다.

### ISSUE1 뒤로가기 버튼 중복 호출
  - TopAppBar의 뒤로가기(종료) 버튼을 연타하면 Home 화면을 넘어가 뒤로가는 경우가 발생합니다.
  - currentDestination이 Home이 아닌 경우에만 뒤로가도록 수정하였습니다.

### ISSUE2 화면 중복 이동
   - 홈 화면에서 session 이동 카드를 TopAppBar 영역에 위치한 후 연타하면 화면이 계속 넘어갑니다.
   - navigate 시 이동할 destination과 currentDestination이 같지 않은 경우에만 이동하도록 함수를 구현하려하였으나
     - contributor 화면에서 AppBar 영역을 터치하여도 투과되어 뒤에 있는 카드가 클릭 되기에
     - TopAppBar에 빈 clickable을 제공하여 클릭 이벤트가 투과하는 것을 방지하였습니다.

## Screenshot
### ISSUE1 뒤로가기 버튼 중복 호출
Before | After
:--: | :--:
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/4679634/bb9e62a2-2d94-4867-aa5e-b4875fa9535e" width="300" /> | <img src="https://github.com/droidknights/DroidKnights2023_App/assets/4679634/34d4cdbc-2688-4a4e-aa18-c7e00bfcb3aa" width="300" />

### ISSUE2 화면 중복 이동
Before | After
:--: | :--:
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/4679634/4cc54592-2e49-4aca-8942-6058f9d18fcc" width="300" /> | <img src="https://github.com/droidknights/DroidKnights2023_App/assets/4679634/04874b67-de20-4cfe-a820-b9cebec7567e" width="300" />

2023-08-31 12:48 UTC, wisemuji requested changes
이슈 제보와 패치, 상세한 테스트 스크린샷까지 감사합니다 🙇 

몇 가지 제안사항이 있으니 확인 부탁드리겠습니다.

2023-08-31 12:48 UTC, wisemuji commented on feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
> +    fun isSameCurrentDestination(route: String) =
`popBackStack`와 `isSameCurrentDestination`는 이제 더 이상 외부에서 참조되지 않으니 private으로 바꾸면 어떨까요?

2023-08-31 12:48 UTC, wisemuji commented on core/designsystem/src/main/java/com/droidknights/app2023/core/designsystem/component/TopAppBar.kt
> +                )
클릭 이벤트 투과 방지 목적이라면 `pointerInput`을 사용하여 포인터 입력 이벤트를 정의하면 어떨까요?
```suggestion
                .pointerInput(Unit) {}
```

KnightsTopAppBar는 클릭 가능하도록 설계할 필요가 없어서 `clickable`을 사용하는 것보다 더 명시적이지 않을까 합니다. `clickable` 내부에서 `pointerInput`을 사용하고 있기도 하고요.

참고로 Surface 컴포저블을 뜯어보면 동일한 로직이 포함되어 있습니다.
```kotlin
fun Surface( /* ... */ ) {
    Box(
        // ...
        .pointerInput(Unit) {},
    ) {
    // ...
}

2023-08-31 13:34 UTC, laco-dev commented on feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
> +        }
홈에서도 뒤로가기혹은 네비게이션 동작이 똑같은 상황을 만들어 낼 수 있지 않을까요?
이 부분은 저도 고민해보지 못한 부분이라 비슷한 내용을 담고 있는 이슈 남겨봤습니다.
- https://github.com/google/accompanist/issues/1320

2023-09-01 14:25 UTC, kisa002 commented on feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
> +        }
근본적으로 방지한다면, Navigate의 경우 PR에 작성해둔 것 처럼
`navigate 시 이동할 destination과 currentDestination이 같지 않은 경우에만 이동`

하도록 구현한다면 전체 상황에 대해서 방지할 수 있습니다.

뒤로가기의 경우에도 호출되는 모든 popBackStack 부분들에 때 의도하는 destination을 넘겨 해당 destination이 아닌 경우에만 뒤로가도록하는 방식을 채택한다면 마찬가지로 근본적으로 수정가능할 것 으로 보입니다. 

다만 전반적으로 하나하나 연타를 해보았을 때 위의 시나리오 외에 중복 호출 되는 곳은 없어 적용하지 않았습니다. 만약 근본적인 차단을 고려하신다면 navigate, popBackStack하는 부분들을 destination을 넘겨 받아 비교 후 처리하도록 구현하도록 하겠습니다. 😃

2023-09-01 14:25 UTC, kisa002 commented on core/designsystem/src/main/java/com/droidknights/app2023/core/designsystem/component/TopAppBar.kt
> +                )
pointerInput을 사용할 생각을 못했네요 감사합니다 수정하도록 하겠습니다 😃

2023-09-01 14:27 UTC, kisa002 commented on feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
> +    fun isSameCurrentDestination(route: String) =
혹시나 사용하는 경우가 생길 수 있지 않을까 생각하고 public으로 두었는데, 생각해보니 필요한 경우에 바꿔 사용하면 되겠네요.
반영하도록 하겠습니다.

2023-09-01 14:37 UTC, kisa002 commented
남겨주신 리뷰 반영하였습니다! 😁

2023-09-01 15:16 UTC, wisemuji approved these changes
고생 많으셨습니다 👏

2023-09-04 02:29 UTC, laco-dev commented on feature/main/src/main/java/com/droidknights/app2023/feature/main/MainNavigator.kt
> +        }
넵, 아직은 확실하지 않은 기능이고 버그에 대한 이슈이므로 이정도로 괜찮을 것 같습니다.
확인 감사합니다

2023-09-04 02:29 UTC, laco-dev approved these changes

2023-09-04 02:29 UTC, merged